title: Why are you here?
description: > # this means to ignore newlines until "baseurl:"
  Random musings, shitposting, and miscellaneous thoughts from a random highschooler vaguely interested in computers.
permalink: ':title/'
baseurl: "/random-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: artemsheludko/flexible

# Author Settings
author: Sohal Sudheer # add your name
author-img: david-freeman.jpg # add your photo
about-author: Said random highschooler from site description. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: sohalsdr # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address


# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
